apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-penguins
  namespace: kubeflow-user-example-com
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi