apiVersion: v1
kind: Secret
metadata:
  name: s3secret
  namespace: model-deploy
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  AWS_ENDPOINT_URL: http://minio-service.kubeflow.svc:9000
  USE_SSL: "false"